name: CI/CD Básico

on:
  push:
    branches:
      - Isaac_citas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Generar build
        run: npm run build

      - name: Despliegue simulado
        run: echo "Deploy exitoso"
